import { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import Topbar from '@/components/Topbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <main className="flex justify-center min-h-[calc(100vh-5rem)] h-full">
          <div className="max-w-screen-lg w-full py-9">{children}</div>
        </main>
      </body>
    </html>
  );
}
